name: Poetry
on: [push]

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install poetry
      run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH=$PATH:/.local/share/pypoetry/venv/bin/
          poetry self update
    - name: Poetry dependencies
      run: |
        poetry add safety
        poetry add coverage
    - name: Poetry run safety
      run: poetry run safety check
    - name: Poetry run coverage
      run: poetry run coverage run


