name: Safety
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: pyupio/safety
        uses: pyupio/safety@2.3.1
